//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YURI.CLOUD.TEST.WEBAPP.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DefaultMenssage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultMenssage() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YURI.CLOUD.TEST.WEBAPP.Resources.DefaultMenssage", typeof(DefaultMenssage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de aplicación es invalido para generar una clave.
        /// </summary>
        public static string CodAplicacion_GenerarClavesNoExiste {
            get {
                return ResourceManager.GetString("CodAplicacion_GenerarClavesNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró su sesión de usuario, favor vuelva a ingresar sus credenciales de acceso.
        /// </summary>
        public static string CodEstadoHTTP_404 {
            get {
                return ResourceManager.GetString("CodEstadoHTTP_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error no paso la validación AntiForgeryToken.
        /// </summary>
        public static string CrossSiteRequestForgery {
            get {
                return ResourceManager.GetString("CrossSiteRequestForgery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es valida su sesión de usuario.
        /// </summary>
        public static string DATOINVALIDO_0001 {
            get {
                return ResourceManager.GetString("DATOINVALIDO_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algunos campos enviados en la solicitud no son válidos, favor verifique.
        /// </summary>
        public static string DATOINVALIDO_0026 {
            get {
                return ResourceManager.GetString("DATOINVALIDO_0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información enviada es incorrecta..
        /// </summary>
        public static string DATOINVALIDO_0027 {
            get {
                return ResourceManager.GetString("DATOINVALIDO_0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información enviada está incompleta, verifique los campos requeridos..
        /// </summary>
        public static string DATOINVALIDO_0028 {
            get {
                return ResourceManager.GetString("DATOINVALIDO_0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Token enviado es invalido.
        /// </summary>
        public static string DATOINVALIDO_0029 {
            get {
                return ResourceManager.GetString("DATOINVALIDO_0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Token de la transacción es invalido.
        /// </summary>
        public static string DATOINVALIDO_0030 {
            get {
                return ResourceManager.GetString("DATOINVALIDO_0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campaña es invalida, favor verifique los datos enviados..
        /// </summary>
        public static string DATOINVALIDO_CAMP_0001 {
            get {
                return ResourceManager.GetString("DATOINVALIDO_CAMP_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error técnico al invocar servicio REST.
        /// </summary>
        public static string ExcepcionSrvREST {
            get {
                return ResourceManager.GetString("ExcepcionSrvREST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error técnico al obtener la respuesta del servicio REST.
        /// </summary>
        public static string JsonResult_IsNullOrEmpty {
            get {
                return ResourceManager.GetString("JsonResult_IsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Alerta!.
        /// </summary>
        public static string MensajeCabecera_Default {
            get {
                return ResourceManager.GetString("MensajeCabecera_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Favor actualizar su información.
        /// </summary>
        public static string MSJ_Campania_MigracionPlataforma {
            get {
                return ResourceManager.GetString("MSJ_Campania_MigracionPlataforma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cierre de la sesion por LiberarSesionUsuario.
        /// </summary>
        public static string SignOff_LiberarSesionUsuario {
            get {
                return ResourceManager.GetString("SignOff_LiberarSesionUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cierre de la sesion por Logout.
        /// </summary>
        public static string SignOff_Logout {
            get {
                return ResourceManager.GetString("SignOff_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cierre de la sesion por ReLogin (SesionCaducada).
        /// </summary>
        public static string SignOff_ReLogin {
            get {
                return ResourceManager.GetString("SignOff_ReLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cierre de la sesion por SOLV_DesbloquearUsuario.
        /// </summary>
        public static string SignOff_SOLV_DesbloquearUsuario {
            get {
                return ResourceManager.GetString("SignOff_SOLV_DesbloquearUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El contenido del archivo no tiene el formato correcto.
        /// </summary>
        public static string Uploaded_File_ContenidoArchFormatoIncorrecto {
            get {
                return ResourceManager.GetString("Uploaded_File_ContenidoArchFormatoIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error técnico al procesar la importación del archivo.
        /// </summary>
        public static string Uploaded_File_ErrorTecnico {
            get {
                return ResourceManager.GetString("Uploaded_File_ErrorTecnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato del archivo es incorrecto.
        /// </summary>
        public static string Uploaded_File_FormatoIncorrecto {
            get {
                return ResourceManager.GetString("Uploaded_File_FormatoIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se permite múltiples archivos para el proceso.
        /// </summary>
        public static string Uploaded_File_MultiplesArchNoPermitido {
            get {
                return ResourceManager.GetString("Uploaded_File_MultiplesArchNoPermitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay archivo que procesar.
        /// </summary>
        public static string Uploaded_File_NoHayArchivoFormFilesRequest {
            get {
                return ResourceManager.GetString("Uploaded_File_NoHayArchivoFormFilesRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo recuperar su último inicio de sesión, favor comuníquese con el administrador del sistema..
        /// </summary>
        public static string ValidarUsuario_LastSession {
            get {
                return ResourceManager.GetString("ValidarUsuario_LastSession", resourceCulture);
            }
        }
    }
}
