//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YURI.CLOUD.TEST.WEBAPP.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DefaultParameters {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultParameters() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YURI.CLOUD.TEST.WEBAPP.Resources.DefaultParameters", typeof(DefaultParameters).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LoginUsr.
        /// </summary>
        public static string CodAplicacion_GenerarClaves {
            get {
                return ResourceManager.GetString("CodAplicacion_GenerarClaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1906.
        /// </summary>
        public static string CodError_ConsSinInformacion {
            get {
                return ResourceManager.GetString("CodError_ConsSinInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1907.
        /// </summary>
        public static string CodError_ErrorTecnico {
            get {
                return ResourceManager.GetString("CodError_ErrorTecnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 100.
        /// </summary>
        public static string CodEstadoHTTP_100 {
            get {
                return ResourceManager.GetString("CodEstadoHTTP_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 400.
        /// </summary>
        public static string CodEstadoHTTP_400 {
            get {
                return ResourceManager.GetString("CodEstadoHTTP_400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 404.
        /// </summary>
        public static string CodEstadoHTTP_404 {
            get {
                return ResourceManager.GetString("CodEstadoHTTP_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONS_TRACKING01.
        /// </summary>
        public static string CONS_TRACKING01 {
            get {
                return ResourceManager.GetString("CONS_TRACKING01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONS_TRACKING02.
        /// </summary>
        public static string CONS_TRACKING02 {
            get {
                return ResourceManager.GetString("CONS_TRACKING02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MIEMBRO.
        /// </summary>
        public static string DatosMiembroAX_OP_MIEMBRO {
            get {
                return ResourceManager.GetString("DatosMiembroAX_OP_MIEMBRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desbloqueo de usuario bajo demanda.
        /// </summary>
        public static string MotivoSolv_DesbloqUsrBajoDemanda {
            get {
                return ResourceManager.GetString("MotivoSolv_DesbloqUsrBajoDemanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ImgUsr.
        /// </summary>
        public static string Uploaded_ImgUsr {
            get {
                return ResourceManager.GetString("Uploaded_ImgUsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ImportNuevoClientes.
        /// </summary>
        public static string UploadedTipoArch_NuevosClientes {
            get {
                return ResourceManager.GetString("UploadedTipoArch_NuevosClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ImportOrdenesCompra.
        /// </summary>
        public static string UploadedTipoArch_OrdenesCompras {
            get {
                return ResourceManager.GetString("UploadedTipoArch_OrdenesCompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ImportTracking.
        /// </summary>
        public static string UploadedTipoArch_Trackings {
            get {
                return ResourceManager.GetString("UploadedTipoArch_Trackings", resourceCulture);
            }
        }
    }
}
